### ISSUE TITLE
response 404 for message/zh-CN.js

### ISSUE THREAD

**Issue by edwardvon** [takashiro/sanguosha-react#7]
Hello, takashiro. 
I got a "404" for message/zh-CH.js as I start devserver and visit.
And I notice there is a "zh-CN.json" at the message folder of the repository, now I wonder should I copy this to dist/message/.

Please tell me, thanks.

**Comment by edwardvon** [comment]
傻了，没反应过来都是国人。

**Comment by edwardvon** [comment]
自行修改已经解决

**Comment by takashiro** [comment]
抱歉没及时更新README和package.json。
运行`npx linguist release`会从`message/*.json`生成`dist/message/*.js`。
运行`npx linguist update`会从TypeScript源文件中把新增的react-intl更新到`message/*.json`。
