### ISSUE TITLE
创建房间后无法正常进行游戏

### ISSUE THREAD

**Issue by edwardvon** [takashiro/sanguosha-react#8]
您好，如题成功把服务端、客户端跑起来后，创建房间后进入了新画面，只有一个“确认”button，点击没有作用。

打log发现此时的generals为空列表，请问应该如何解决？

**Comment by takashiro** [comment]
应该是 https://github.com/takashiro/karuta-node-server/commit/03cfe0d77c104191e0a09b4a14728f12371c9ca1 改变了扩展加载的方式。之前一直在canary分支工作，pull一下最新dev看看。对应修改为 23618e92daca7825350ceb827dfda841136daf69

**Comment by takashiro** [comment]
对了，目前仅初步完成了标准包的基本牌和锦囊牌。思路卡在技能系统了，装备牌无技能，武将无技能。AI没有写，只会摸牌弃牌。

**Comment by edwardvon** [comment]
> 对了，目前仅初步完成了标准包的基本牌和锦囊牌。思路卡在技能系统了，装备牌无技能，武将无技能。AI没有写，只会摸牌弃牌。

题目问题解决。我看看能不能看懂系统的代码，我尝试写写。谢谢大佬
